package com.unicauca.figures.domain.presentation;

import com.unicauca.figures.domain.models.Triangle;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class GUITriangle extends javax.swing.JFrame {

    /**
     * Creates new form GUITriangle
     */
    public GUITriangle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBase = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        lbSide1 = new javax.swing.JLabel();
        txtSide1 = new javax.swing.JTextField();
        lbSide2 = new javax.swing.JLabel();
        txtSide2 = new javax.swing.JTextField();
        lbArea = new javax.swing.JLabel();
        lbPerimeter = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(8, 0));

        lbBase.setText("Enter Base");
        jPanel1.add(lbBase);
        jPanel1.add(txtBase);

        lbSide1.setText("Enter Side 1");
        jPanel1.add(lbSide1);
        jPanel1.add(txtSide1);

        lbSide2.setText("Enter Side 2");
        jPanel1.add(lbSide2);
        jPanel1.add(txtSide2);

        lbArea.setText("Area:");
        jPanel1.add(lbArea);

        lbPerimeter.setText("Perimeter:");
        jPanel1.add(lbPerimeter);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout());

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalculate);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try{
            double prmBase, prmSide1, prmSide2;
            prmBase = Double.parseDouble(txtBase.getText());
            prmSide1 = Double.parseDouble(txtSide1.getText());
            prmSide2 = Double.parseDouble(txtSide2.getText());

            Triangle objTriangle = new Triangle(prmBase,prmSide1,prmSide2);

            lbArea.setText("Area: "+objTriangle.calculateArea());
            lbPerimeter.setText("Perimeter: "+objTriangle.calculatePerimeter());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "No se pudo hacer el cálculo con datos vacíos");
        }
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITriangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbBase;
    private javax.swing.JLabel lbPerimeter;
    private javax.swing.JLabel lbSide1;
    private javax.swing.JLabel lbSide2;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtSide1;
    private javax.swing.JTextField txtSide2;
    // End of variables declaration//GEN-END:variables
}
